[package]
name = "droid-wrap-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
heck = "0.5.0"
proc-macro2 = "1.0.85"
quote = "1.0.36"

[dependencies.syn]
features = ["full"]
version = "2.0.66"

[lib]
proc-macro = true