[package]
name = "droid-wrap-utils"
authors.workspace = true
keywords.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
jni = "0.21.1"
ndk-context = "0.1.1"